name: automatic-api-review
 
on:
  push:
    branches:
      - "bugfix/*"
 
jobs:
  automatic-api-review-workflow:
    uses: DPA-APIS/action-fix-design/.github/workflows/automatic-api-review-workflow.yaml@fix-fase02
    secrets: inherit
   